# .github/workflows/deploy-locaweb.yml (v1.3 - Caminhos Corrigidos)

name: Deploy to Locaweb via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend and Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend
        # Navega para o novo local do frontend antes de compilar
        run: |
          cd app_engine/frontend
          npm install
          npm run build

      - name: FTP Deploy to Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.LW_HOST }}
          user: ${{ secrets.LW_USER }}
          password: ${{ secrets.LW_PASS }}
          
          # Aponta para a pasta 'dist' no novo local
          localDir: "app_engine/frontend/dist"
          
          # Aponta para o diretório final no servidor
          remoteDir: "public_html/mcp/meshwave/project_c3"

