# .github/workflows/deploy-locaweb.yml

name: Deploy to Locaweb via FTP

# Gatilho: Executa esta ação sempre que houver um push no branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend and Config
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do seu repositório para a máquina virtual do GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configura o Node.js para poder compilar o frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Use uma versão LTS do Node

    # 3. Compila o projeto do frontend para gerar a pasta 'dist'
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    # 4. Faz o deploy da pasta 'dist' para a Locaweb usando FTP
    - name: FTP Deploy to Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        # Usa os segredos que configuramos no GitHub
        host: ${{ secrets.LW_HOST }}
        user: ${{ secrets.LW_USER }}
        password: ${{ secrets.LW_PASS }}
        
        # Diretório local (a pasta que queremos enviar)
        localDir: "frontend/dist" 
        
        # Diretório remoto (onde os arquivos devem ir na Locaweb)
        # Geralmente 'public_html' ou 'www'. Verifique no seu painel.
        remoteDir: "public_html" 

